-- SQL TABLE CREATION VALUES

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


ALTER TABLE `migration_test` CHANGE `banned` `banned2` TINYINT(1) NOT NULL DEFAULT '0';



COMMIT;
